### ISSUE TITLE
Can't Play Destiny 2, Please Help!

### ISSUE THREAD

**Issue by InsaneBeats** [lax20attack/destiny-dashboard#10]
i bought the destiny 2 deluxe edition bundle and the count down for playing it has well been over and i still cant play the damn game. I have it on battle.net so bungie better get their shit together or im getting a refund for my $100 fucking dollars... sincerely -Unsatisfied Customer.

**Comment by lax20attack** [comment]
Not sure if you're serious, but PC doesn't release for a while.

**Comment by InsaneBeats** [comment]
thats stupid. i didnt see anything telling me that information when i bought the game.
