### ISSUE TITLE
Clan Leaderboards

### ISSUE THREAD

**Issue by TempestRex** [lax20attack/destiny-dashboard#12]
Seems that the clan leaderboards is not working at all any more.  It worked when I first downloaded the android app but now it is just blank and also doesn't work on the full site.  Not sure if Bungie changed the API and that's the reason it's not working.  Just curious because I found it to be a neat feature.

Also just wanted to say this is an awesome app.  So much info all in one place.

Thanks!!!

**Comment by vpzed** [comment]
Thanks for the problem report. I'll take a look this evening and see what is going on.

**Comment by vpzed** [comment]
@TempestRex The Clan Leaderboards API endpoint is not working at the moment.  I have [opened an issue with the Bungie API team](https://github.com/Bungie-net/api/issues/182) so they can investigate.

**Comment by TempestRex** [comment]
Wow.  That was fast.  Hopefully they fix it soon.  It's not something
essential but it was neat to see and promoted some friendly competition
inside the clan as well.  Thanks for checking on that.

**Comment by vpzed** [comment]
Bungie turned the Clan Leaderboards endpoint back on with today's maintenance so the card is working again.

**Comment by TempestRex** [comment]
Awesome.  I'll have to check it out.

**Comment by TempestRex** [comment]
Definitely working now.  Awesome.  Again great app.
