### ISSUE TITLE
Dashboard not starting

### ISSUE THREAD

**Issue by Doomking99** [lax20attack/destiny-dashboard#13]
On Android and Chrome on Windows Destiny Dashboard does not start. It shows the default dashboard and the circle but it never opens and does not offer login. It worked before

**Comment by cfremgen** [comment]
Hi, The dashboard has been abandoned. I'm going to close this repo. Sorry, there just wasn't enough developer interest and not enough users to justify the time needed to maintain.

**Comment by lax20attack** [comment]
Hi, The dashboard has been abandoned. I'm going to close this repo. Sorry, there just wasn't enough developer interest and not enough users to justify the time needed to maintain.
